name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    strategy:
      fail-fast: false
      matrix:
        module-path:
          - S1-Stack-LIFO
          - S2-Stack-Impl
          - S3-Balanced-Parentheses
          - S4-Infix-To-Postfix
          - S5-Two-Stacks-One-Array
          - S6-Sort-Stack-Using-Stacks
          - S7-Min-Stack
          - S10-Browser-History
          - L1-Arrays-vs-LinkedLists
          - L2-Implement-SLL
          - L3-Reverse-LinkedList
          - L4-Detect-Cycle
          - L5-Find-Middle
          - L6-Merge-Two-Sorted-Lists
          - L7-Remove-Nth-From-End
          - L8-Intersection
          - L9-Palindrome-LinkedList
          - L10-Flatten-Multilevel
          - L13-Reorder-List
          - C1-Stack-Complexity
          - C2-LinkedList-Pitfalls

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # run mvn test for this specific module
      - name: run unit tests
        id: run-unit-tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          # This label will show up in the Classroom score output
          test-name: "Tests for ${{ matrix.module-path }}"
          setup-command: ""
          command: mvn -f ${{ matrix.module-path }}/pom.xml -B -ntp -DfailIfNoTests=true test
          timeout: 30
          max-score: 100

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: run-unit-tests
